### ISSUE TITLE
Master is throwing an error when running 'interactive' command

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/o2#38]
~~~shell
info-rchitect:/mnt/c/o2/example$ git pull origin master
From https://github.com/Origen-SDK/o2
 * branch            master     -> FETCH_HEAD
Already up to date.
info-rchitect:/mnt/c/o2/example$ origen i
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/c/o2/python/origen/init.py", line 2, in <module>
    import _origen
ModuleNotFoundError: No module named '_origen'
~~~

**Comment by ginty** [comment]
Did you compile the Rust extension?

**Comment by info-rchitect** [comment]
@ginty thx, I swear I had done that.
